package com.dev.snaplog.Presentaion

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Button
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.dev.snaplog.R


@Preview(showBackground = true, showSystemUi = true)
@Composable
fun Welcome(modifier: Modifier = Modifier) {
    Scaffold(

    ) { paddingValues->
        Column (
            modifier = Modifier.fillMaxSize().padding(paddingValues).padding(
                horizontal = 20.dp
            ),
            horizontalAlignment = Alignment.CenterHorizontally,
           verticalArrangement = Arrangement.Center
        ){
            Spacer(modifier = Modifier.weight(0.5f))
            Image(
                modifier = Modifier.size(300.dp),
                painter = painterResource(
                    id = R.drawable.welcome
                ),
                contentDescription = null
            )
            Spacer(modifier = Modifier.height(20.dp))
            Text(text = "How Our App Works",
                fontWeight = FontWeight.Bold,
                fontSize = 24.sp)
            Spacer(modifier = Modifier.height(10.dp))
            Text(
                text = "Your data is safe. Your images will not be uploaded to the cloud. " +
                        "The text will be extracted from the image on device but not stored anywhere." +
                        " The title and description will be generated by AI." +
                        "Allow the Permission to proceed",
                overflow = TextOverflow.Clip,
                textAlign = TextAlign.Center,
                fontWeight = FontWeight.Medium,
              //  modifier = Modifier.padding(horizontal = 20.dp)
            )
            Spacer(modifier = Modifier.weight(1f))

            Button(onClick = {},
                modifier = Modifier.align(Alignment.End)) {
                Text(text = "Allow ")
            }

        }
    }
}